const institutions = [
    "Acharya Nagarjuna University",
    "Aditya College of Engineering",
    "Aditya Engineering College",
    "Aditya Institute of Technology and Management",
    "Aizza College of Engineering and Technology",
    "Akula Sree Ramulu College of Engineering",
    "Alfa College of Engineering",
    "Amalapuram Engineering College",
    "Amrita Sai Institute of Science and Technology",
    "Amrita Vishwa Vidyapeetham",
    "Anantha Lakshmi Institute of Technology and Sciences",
    "Andhra Loyola College",
    "Andhra University",
    "Andhra University College of Engineering",
    "Annamacharya Institute of Technology and Sciences",
    "Annamalai University",
    "Annapurna Engineering College",
    "Anurag College of Engineering",
    "Anurag Group of Institutions",
    "Anurag University",
    "Apex Engineering College",
    "Arjun College of Technology",
    "Arunai Engineering College",
    "Ashoka Women's Engineering College",
    "Aurora's Engineering College",
    "Aurora's Scientific and Technological Institute",
    "AVN Institute of Engineering and Technology",
    "Bapatla Engineering College",
    "Bharath Institute of Higher Education and Research",
    "Bharati Vidyapeeth University College of Engineering",
    "Bhoj Reddy Engineering College for Women",
    "BITS Pilani Hyderabad Campus",
    "Borrugadda Engineering College",
    "Bonam Venkata Chalamayya Institute of Technology and Science",
    "Buddha Institute of Technology",
    "BVC Engineering College",
    "BVR Institute of Technology",
    "CBIT - Chaitanya Bharathi Institute of Technology",
    "Central University of Andhra Pradesh",
    "Central University of Hyderabad",
    "Chalapathi Institute of Engineering and Technology",
    "Chaitanya Engineering College",
    "Chaitanya Institute of Science and Technology",
    "Chandra Shekhar Azad University of Agriculture and Technology",
    "Christ University",
    "CMR College of Engineering and Technology",
    "CMR Engineering College",
    "CMR Institute of Technology",
    "CMR Technical Campus",
    "CVR College of Engineering",
    "Dadi Institute of Engineering and Technology",
    "Dayananda Sagar College of Engineering",
    "DMSSVH College of Engineering",
    "Dr. Samuel George Institute of Engineering and Technology",
    "DVR College of Engineering and Technology",
    "Eluru College of Engineering and Technology",
    "Eswar College of Engineering",
    "Farah Institute of Technology",
    "G Narayanamma Institute of Technology and Science",
    "G Pullaiah College of Engineering and Technology",
    "G Pulla Reddy Engineering College",
    "Gayatri Vidya Parishad College of Engineering",
    "Geethanjali College of Engineering and Technology",
    "Geethanjali Institute of Science and Technology",
    "GITAM University",
    "GMR Institute of Technology",
    "Godavari Institute of Engineering and Technology",
    "Gokaraju Rangaraju Institute of Engineering and Technology",
    "Gopal Reddy Engineering College",
    "Government College of Engineering Anantapur",
    "Government College of Engineering Kakinada",
    "Government College of Engineering Rajahmundry",
    "Government College of Engineering Tirupati",
    "Gudlavalleru Engineering College",
    "Guru Nanak Institute of Technology",
    "Guru Nanak Institutions Technical Campus",
    "HITAM - Hyderabad Institute of Technology and Management",
    "Holy Mary Institute of Technology and Science",
    "ICFAI Foundation for Higher Education",
    "IIIT Hyderabad",
    "IIIT Kancheepuram",
    "IIIT Kurnool",
    "IIIT Nuzvidu",
    "IIIT Raichur",
    "IIIT Srikakulam",
    "IIT Hyderabad",
    "IIT Tirupati",
    "Indian Institute of Science Education and Research",
    "Institute of Aeronautical Engineering",
    "International Institute of Information Technology",
    "ISB Hyderabad",
    "JBIET - J B Institute of Engineering and Technology",
    "Jawaharlal Nehru Technological University Anantapur",
    "Jawaharlal Nehru Technological University Hyderabad",
    "Jawaharlal Nehru Technological University Kakinada",
    "Jeppiaar Engineering College",
    "JNTU College of Engineering Anantapur",
    "JNTU College of Engineering Hyderabad",
    "JNTU College of Engineering Jagityal",
    "JNTU College of Engineering Kakinada",
    "JNTU College of Engineering Vizianagaram",
    "Joginpally B R Engineering College",
    "K L University",
    "Kakatiya Institute of Technology and Science",
    "Kakatiya University",
    "Kammavari Sangham Institute of Technology",
    "Kamoj College of Engineering and Technology",
    "Karpagam Academy of Higher Education",
    "Kasireddy Narayan Reddy College of Engineering and Research",
    "Keshav Memorial Institute of Technology",
    "KG Reddy College of Engineering and Technology",
    "Khammam Institute of Technology and Sciences",
    "KITS Warangal",
    "Kommuri Pratap Reddy Institute of Technology",
    "Koneru Lakshmaiah Education Foundation",
    "Krishna Chaitanya Institute of Technology and Sciences",
    "Krishna University",
    "Kuppam Engineering College",
    "Laki Reddy Balireddy College of Engineering",
    "Lakireddy Bali Reddy College of Engineering",
    "Loyola Academy",
    "Madanapalle Institute of Technology and Science",
    "Mahatma Gandhi Institute of Technology",
    "Mahindra University",
    "Malla Reddy College of Engineering and Technology",
    "Malla Reddy Institute of Engineering and Technology",
    "Malla Reddy Engineering College for Women",
    "Manipal Academy of Higher Education",
    "Marri Laxman Reddy Institute of Technology and Management",
    "Methodist College of Engineering and Technology",
    "Mina Institute of Engineering and Technology for Women",
    "Mohan Babu University",
    "Motherhood University",
    "MRR Institute of Technology and Science",
    "MVGR College of Engineering",
    "MVJ College of Engineering",
    "MVSR Engineering College",
    "Nagarjuna College of Engineering and Technology",
    "Nalanda Institute of Engineering and Technology",
    "Narayana Engineering College",
    "Narasaraopeta Engineering College",
    "Neil Gogte Institute of Technology",
    "NETE Group of Institutions",
    "Netaji Institute of Engineering and Technology",
    "Nimra College of Engineering and Technology",
    "NIT Andhra Pradesh",
    "NIT Warangal",
    "NRIIT - NRI Institute of Technology",
    "NRT Institute of Technology",
    "Osmania University",
    "Padmasri Dr B V Raju Institute of Technology",
    "Pallavi Engineering College",
    "PBR Visvodaya Institute of Technology and Science",
    "PERI Institute of Technology",
    "PES College of Engineering",
    "Prasad V Potluri Siddhartha Institute of Technology",
    "Princeton College of Engineering and Technology",
    "Pydah College of Engineering",
    "Qis College of Engineering and Technology",
    "R V R and J C College of Engineering",
    "Raghu Engineering College",
    "Raghu Institute of Technology",
    "Rajam Institute of Technology",
    "Rajahmundry Institute of Engineering and Technology",
    "Rajamahendravaram Institute of Engineering and Technology",
    "Rajiv Gandhi University of Knowledge Technologies",
    "Ramachandra College of Engineering",
    "Ramappa Engineering College",
    "RMK College of Engineering and Technology",
    "RVRJC College of Engineering",
    "Sai Ganapathi Engineering College",
    "Sai Spurthi Institute of Technology",
    "Samskruti College of Engineering and Technology",
    "Sarada Institute of Science Technology and Management",
    "Saveetha School of Engineering",
    "Scient Institute of Technology",
    "Siddharth Institute of Engineering and Technology",
    "Siddartha Educational Academy Group of Institutions",
    "Sir C R Reddy College of Engineering",
    "SITS - Siddhartha Institute of Technology and Sciences",
    "Sphoorthy Engineering College",
    "Sree Chaitanya College of Engineering",
    "Sree Chaitanya Institute of Technological Sciences",
    "Sree Dattha Institute of Engineering and Science",
    "Sree Kavitha Engineering College",
    "Sree Nidhi Institute of Science and Technology",
    "Sree Rama Engineering College",
    "Sree Vahini Institute of Science and Technology",
    "Sreenidhi Institute of Science and Technology",
    "Sri Chaitanya College of Engineering",
    "Sri Indu College of Engineering and Technology",
    "Sri Krishnadevaraya University",
    "Sri Mittapalli College of Engineering",
    "Sri Padmavati Mahila Visvavidyalayam",
    "Sri Sivani College of Engineering",
    "Sri Venkateswara College of Engineering",
    "Sri Venkateswara Institute of Science and Technology",
    "Sri Venkateswara University",
    "SRKR Engineering College",
    "SRM University AP",
    "Stanley College of Engineering and Technology for Women",
    "Swarnandhra College of Engineering and Technology",
    "Teegala Krishna Reddy Engineering College",
    "TKR College of Engineering and Technology",
    "Tirumala Engineering College",
    "Usha Rama College of Engineering and Technology",
    "V R Siddhartha Engineering College",
    "Vaagdevi College of Engineering",
    "Vardhaman College of Engineering",
    "Vasavi College of Engineering",
    "Vasireddy Venkatadri Institute of Technology",
    "Velagapudi Ramakrishna Siddhartha Engineering College",
    "Vidya Bharathi Institute of Technology",
    "Vidya Jyothi Institute of Technology",
    "Vignan Institute of Information Technology",
    "Vignan Institute of Technology and Aeronautical Engineering",
    "Vignan University",
    "Vignan's Foundation for Science Technology and Research",
    "Vignan's Institute of Engineering for Women",
    "Vignan's Institute of Information Technology",
    "Vignan's Institute of Management and Technology for Women",
    "Vignan's Lara Institute of Technology and Science",
    "Vignan's Nirula Institute of Technology and Science for Women",
    "VIT AP University",
    "Vivekananda Institute of Technology and Science",
    "VNR Vignana Jyothi Institute of Engineering and Technology",
    "Warangal Institute of Technology and Science",
    "Woxsen University",
    "Yogi Vemana University",
    "Other"
];

export default institutions;
  