name: Deploy Frontend to Cloudflare Pages

on:
  push:
    branches: [ main ]
    paths:
      - 'client-test/**'
      - '.github/workflows/deploy-frontend.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Cloudflare Pages
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: 'client-test/package-lock.json'

      - name: Install dependencies
        run: |
          cd client-test
          npm ci

      - name: Build application
        run: |
          cd client-test
          npm run build
        env:
          VITE_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL }}

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: codequest-frontend
          directory: client-test/dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}